from service.bigdata.OOP.hms.exception import *
# animal = Liger()
# animal.cry() # 다형성, 윗쪽에있는 함수에 적용해서 반환
# animal.jump()
# animal.bite()
# animal.play()

# base = Base() #추상클래스에서는 인스턴스를 못만듬. 상속해서 내려주려고 만듬
# base = BaseSub()
# base.study()
# base.goToAcademy()

# print('error)
# print('success')

# a = 10
# b = 20
# print(c)

# print(100/0)
# print('end')

# list = [50, 70, 90]
# print(list[4])
# print('end')

# dic = {'name': 'jslim', 'age': 48, 'address':'seoul'}
# print(dic['Name']) #key로 가져오는 방법
# print(dic.get('Name')) # error를 발생시키지 않음

# file = open('c:/test.text')

# x = [1,2]
# y = (1,2)
# z = 'test'
# print(x+list(y))

# userInput()
# print('after userINput()')

# list01 = [1,2]
# exceptionFunc(list01)
#
# list01 = [1,2,3,-100]
# exceptionFunc(list01)

list = [10,20,25, 'num', 40,50]
listExcepFunc(list)